import type { NextPage } from 'next'
import Head from 'next/head'
import WalletConnect from '../components/WalletConnect'
import NavBar from '../components/NavBar'
import SideNav from '../components/SideNav'
import { useStoreActions, useStoreState } from "../utils/store"
import Link from 'next/link'
import { useState, useEffect } from 'react'
import { getAssets } from "../utils/cardano";
import NftGrid from "../components/NftGrid";
import initLucid from '../utils/lucid'
import Layout from '../components/Layout'

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.walletModel.wallet)
  const [nftList, setNftList] = useState([])
  const [balance, setBalance] = useState()
  const [isLoading, setIsLoading] = useState(true) // Add a loading state


  useEffect(() => {
    //const lucid = initLucid(walletStore.name)
    if (walletStore.address != "") {
      setIsLoading(true) // Set loading to true when fetching data
      console.log("Wallet Address: ---"+walletStore.address)
      getAssets(walletStore.address)
        .then((res: any) => {
          setNftList(res.addressInfo.nfts),
          setBalance(res.addressInfo.balance),
          setIsLoading(false) // Set loading to false after data is fetched
        })

        console.log("Wallet Balance: ---"+balance)

      // .then((res: any) => { setBalance(res.addressInfo.balance) })
    }
    else {
      setIsLoading(false) // Set loading to false if there's no address
    }
  }, [walletStore.address])

  if (isLoading) {
    return <div>Loading...</div> // Render a loading message while fetching data
  }

  return (
    <Layout className='bg-white'>
      <Head>
        <title>Cardano dapp quickstart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-10 ">
      <div>Address: {walletStore.address}</div>
      <div>Balance: {balance}</div>
        <div className="mx-40 my-10">
        <h2>Your NFTs:</h2>
          <NftGrid nfts={nftList} />
        </div>
      </div>
    </Layout>
    
  )
}

export default Home
